In [6]:
#import numpy
import numpy as np

a = np.array([1,3,5],dtype='int8') #dtype is for specifing data type
b = np.array([1,2,3])

print(a*b)

[ 1  6 15]


In [7]:
#get dimension
a.ndim

1

In [8]:
a.shape

(3,)

In [9]:
#get type
a.dtype

dtype('int8')

In [10]:
a.nbytes #total sizes

3

In [11]:
a = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
print(a)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [12]:
# to get ith row and jth column we wrire a[i][j]
a[1][3]

5

In [13]:
for i in range(len(a)):
    for j in range(len(a[0])):
        print(a[i][j], end=" ")
    print("")

1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 


In [14]:
#getting a specific row
a[0, :]

array([1, 2, 3, 4, 5])

In [17]:
#getting specific column
a[: ,3]

array([4, 5, 6])

In [22]:
#[startindex:endindex:spetsize]
a[0,0:6:2]

array([1, 3, 5])

In [23]:
a[1][3] = 100

In [24]:
a

array([[  1,   2,   3,   4,   5],
       [  2,   3,   4, 100,   6],
       [  3,   4,   5,   6,   7]])

In [26]:
#copying array

z = np.array([1,2,3])
x = np.array(z)
x[1] = 0
z

array([1, 2, 3])

In [27]:
#mathematics in numpy

np.sin(z)

array([0.84147098, 0.90929743, 0.14112001])

In [30]:
#linear algebra

a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [31]:
#statistics

stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.min(stats[1])

4

In [34]:
#reorganising arrays

before = np.array([[1,2,2,4],[2,5,3,6]])
before.shape

(2, 4)

In [37]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [2, 4]],

       [[2, 5],
        [3, 6]]])

In [41]:
#stacking vector
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,6,7,8,9])

v3 = np.vstack([v1,v2,v1,v2,v1])
v3.shape
v3

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])