In [1]:
import numpy as np

In [6]:
arr = np.arange(11); arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [8]:
arr.max()

10

In [12]:
b = np.arange(5, 46, 5).reshape(3,3); b

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
c = b[:-1,:-1]; c

array([[ 5, 10],
       [20, 25]])

In [19]:
np.random.randn(25)

array([ 1.62302786,  1.99657494, -0.10186582, -1.26913833, -0.63307075,
       -0.57148988, -1.69347823, -0.20517986,  2.06113291,  0.45204401,
       -0.77680377,  1.10614283,  1.14589205,  0.21648671, -0.78325023,
        1.10303809, -0.94287584, -1.08404645, -0.22080617,  0.62917971,
        0.48058084, -0.93217762,  2.30612179,  0.21271645, -1.48929817])